#pragma config(Motor, port1, frontR, tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor, port2, frontL, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor, port3, ShootingR, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor, port4, ShootingL, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor, port9, backR, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor, port10, backL, tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//
#pragma platform(VEX)
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)
#include "Vex_Competition_Includes.c" //Main competition background code...do not modify!
void left(int speed = 63, int cm = 0){//moves left for a designated distance
	//clear();
	if (cm == 0){
		motor[frontR] = speed;
		motor[backR] = -speed;
		motor[frontL] = -speed;
		motor[backL] = speed;
	}
	//else{
	// dist = cm / convertfactor;
	// while (nMotorEncoder[backL]<dist && nMotorEncoder[backR]<dist){
	// motor[frontR] = speed;
	// motor[backR] = -speed;
	// motor[frontL] = -speed;
	// motor[backL] = speed;
	// }
	// halt();
	//}
}
void right(int speed = 63, int cm = 0){//see above, but moves right
	//clear();
	if (cm == 0){
		motor[frontR] = -speed;
		motor[backR] = speed;
		motor[frontL] = speed;
		motor[backL] = -speed;
	}
	//else{
	// dist = cm / convertfactor;
	// while (nMotorEncoder[backL]<dist && nMotorEncoder[backR]<dist){
	// motor[frontR] = -speed;
	// motor[backR] = speed;
	// motor[frontL] = speed;
	// motor[backL] = -speed;
	// }
	// halt();
	//}
}
/////////////////////////////////////////////////////////////////////////////////////////
//
// Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}
/////////////////////////////////////////////////////////////////////////////////////////
//
// Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// ....................................................................................
	while (bIfiAutonomousMode)
	{
		// non-stop shooting mech
		motor[ShootingR] = 127;
		motor[ShootingL] = -127;
	}
}
/////////////////////////////////////////////////////////////////////////////////////////
//
// User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////
task usercontrol()
{
	// User control code here, inside the loop
	while (true)
	{
		// next 4 lines are just regular drive program
		motor[frontR] = vexRT[Ch2];
		motor[frontL] = vexRT[Ch3];
		motor[backR] = vexRT[Ch2];
		motor[backL] = vexRT[Ch3];
		//next 9 lines are for shooting mechanism
		if (vexRT[Btn6D] == 1)
		{
			motor[ShootingR] = 127;
			motor[ShootingL] = -127;
		}
		else{

			motor[ShootingR] = 0;
			motor[ShootingR] = 0;
		}
		if (vexRT[Btn5U] == 1){
			left(127);
		}
		else if (vexRT[Btn6U] == 1){
			right(127);
		}
	}
}
